# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: objective-c

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=macOS'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 4K (at 1080p)'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace SimpleStore.xcworkspace -scheme SimpleStore-MacTests -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty
